version: '2'
services:
  master:
    build:
      context: .
        args:
          - http_proxy=${http_proxy}
          - https_proxy=${https_proxy}
    environment:
      JAVA_OPTS: "-Djava.awt.headless=true"
    ports:
      - "50000:50000"
      - "8080:8080"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - master-data:/var/jenkins_home
volumes:
  master-data: {}
