version: '2'
services:
  app:
    build:
      args:
        - http_proxy=${http_proxy}
        - https_proxy=${https_proxy}
      context: .
    environment:
      - JAVA_OPTS="-Djava.awt.headless=true"
      - TZ=Asia/Tokyo
    ports:
      - "50000:50000"
      - "50001:8080"
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - master-data:/var/jenkins_home
volumes:
  app-data: {}
